"""

Revision ID: 16734d1c03a8
Revises: 0ade2cfee6ec
Create Date: 2025-03-29 14:35:41.390153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16734d1c03a8'
down_revision: Union[str, None] = '0ade2cfee6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rooms_name', table_name='rooms')
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.create_index('ix_rooms_name', 'rooms', ['name'], unique=True)
    # ### end Alembic commands ###
