"""Add price column to Room

Revision ID: 5a95b4af5cd5
Revises: d30e0f068e7b
Create Date: 2025-03-29 13:37:31.937977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a95b4af5cd5'
down_revision: Union[str, None] = 'd30e0f068e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('image', sa.String(), nullable=True))
    op.execute("UPDATE rooms SET image = 'asdasd' WHERE image IS null;")

    op.alter_column('rooms', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_column('rooms', 'image')
    # ### end Alembic commands ###
