"""downgrade changes

Revision ID: c1a21d9789a0
Revises: d983150d84e7
Create Date: 2025-03-29 19:07:06.287201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a21d9789a0'
down_revision: Union[str, None] = 'd983150d84e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admins_id', table_name='admins')
    op.drop_index('ix_admins_username', table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admins_pkey')
    )
    op.create_index('ix_admins_username', 'admins', ['username'], unique=True)
    op.create_index('ix_admins_id', 'admins', ['id'], unique=False)
    # ### end Alembic commands ###
